name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: ['1.14', '1.15']
    steps:
      - name: Setup App
        uses: actions/checkout@v2
      - name: Using Golang 1.15
        uses: actions/setup-go@v2
        with: 
          # go-version: ${{ matrix.go }}
          go-version: 1.15
      - name: Test App
        run: go test
      - name: Run App
        run: go run math.go
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: renatospaka/fc2.0-ci-go:latest
